import { describe, expect, it } from "bun:test";
import { parseLock, renderClaudeMd, renderLock } from "./generate.ts";
import type { WorkspaceManifest } from "./manifest.ts";

const MANIFEST: WorkspaceManifest = {
  version: 1,
  name: "Checkout Redesign",
  slug: "checkout-redesign",
  description: "Redesign the checkout flow across services.",
  members: [
    {
      name: "storefront",
      path: "../storefront",
      url: "https://github.com/acme/storefront",
      ref: "main",
    },
    { name: "payments", path: "../payments", url: undefined, ref: "develop" },
  ],
  layers: [
    { name: "constitution", path: "docs/constitution.md", description: "Invariant principles" },
    { name: "spec", path: "docs/spec", description: "WHAT and WHY" },
  ],
  skills: ["checkout-redesign-context"],
  sections: [],
  stackPrefix: "checkout-redesign/",
  branchPrefix: "wyattjoh/checkout-redesign/",
};

describe("renderClaudeMd", () => {
  it("renders the exact generated document", () => {
    expect(renderClaudeMd(MANIFEST))
      .toBe(`<!-- GENERATED by the workspaces skill from workspace.yaml.
     Do not edit by hand: edit workspace.yaml, then run \`just sync\`. -->

# Checkout Redesign workspace

Redesign the checkout flow across services.

This repository is a workspace hub. It owns the documentation, decisions,
planning, and agent context for a multi-repo body of work. It is a developer
workflow tool: member repositories carry no committed workflow artifacts.

## Context layers

Load these in order when starting work here (the \`enter\` flow of the
workspaces skill automates this):

| # | Layer | Path | Purpose |
| - | ----- | ---- | ------- |
| 1 | constitution | \`docs/constitution.md\` | Invariant principles |
| 2 | spec | \`docs/spec\` | WHAT and WHY |

The curated index at \`docs/index.md\` annotates everything an agent may load.
If a document is not reachable from the index, it is not workspace context.

## Workspace memory

Before starting any work, read the memory index at \`.claude/memory/MEMORY.md\`
and the entries touching your task. Record new knowledge there the moment it
surfaces (ideas, rejections, surprises, open questions); settled entries
graduate to an ADR, journal entry, or finding. Memory files are committed.

## Member repositories

Paths are relative to this directory (sibling checkouts).

| Member | Path | Base ref | Remote |
| ------ | ---- | -------- | ------ |
| storefront | \`../storefront\` | \`main\` | https://github.com/acme/storefront |
| payments | \`../payments\` | \`develop\` | (none) |

## Conventions

- Stack names in member repos: \`checkout-redesign/<task-slug>\`; branches: \`wyattjoh/checkout-redesign/<task-slug>\`.
- ADRs live in \`docs/adr/\` and are superseded, never edited.
- Every deviation from recorded plans/decisions gets a \`JOURNAL.md\` entry
  before or with the change.
- Work plans live in the hub; member repos never hold committed plan files.
- This file is generated. Edit \`workspace.yaml\` and run \`just sync\`.

## Workspace skills

- \`checkout-redesign-context\` (in \`skills/checkout-redesign-context/\`)

## Commands

Run \`just\` to list tasks. Core recipes: \`just sync\`, \`just status\`,
\`just audit\`, \`just freeze\`, \`just journal\`.
`);
  });

  it("is deterministic for identical manifests", () => {
    expect(renderClaudeMd(MANIFEST)).toBe(renderClaudeMd({ ...MANIFEST }));
  });

  it("appends manifest sections after the generated sections", () => {
    const rendered = renderClaudeMd({
      ...MANIFEST,
      sections: [
        { title: "Review site", body: "An Astro site in `src/`. Run it with `just site`." },
        { title: "Runtime", body: "Bun 1.2 or newer." },
      ],
    });
    expect(
      rendered.endsWith(`\`just audit\`, \`just freeze\`, \`just journal\`.

## Review site

An Astro site in \`src/\`. Run it with \`just site\`.

## Runtime

Bun 1.2 or newer.
`),
    ).toBe(true);
  });

  it("renders nothing extra when no sections are declared", () => {
    expect(renderClaudeMd({ ...MANIFEST, sections: [] })).toBe(renderClaudeMd(MANIFEST));
  });

  it("trims surrounding whitespace from a section body", () => {
    const rendered = renderClaudeMd({
      ...MANIFEST,
      sections: [{ title: "Runtime", body: "\n\nBun 1.2 or newer.\n\n" }],
    });
    expect(rendered.endsWith("\n## Runtime\n\nBun 1.2 or newer.\n")).toBe(true);
  });
});

describe("renderLock / parseLock", () => {
  it("renders members sorted by name", () => {
    const rendered = renderLock([
      { name: "storefront", ref: "main", sha: "b".repeat(40) },
      { name: "payments", ref: "develop", sha: "a".repeat(40) },
    ]);
    expect(rendered).toBe(
      `version: 1\nmembers:\n  - name: payments\n    ref: develop\n    sha: ${"a".repeat(40)}\n  - name: storefront\n    ref: main\n    sha: ${"b".repeat(40)}\n`,
    );
  });

  it("round-trips through parseLock", () => {
    const entries = [
      { name: "payments", ref: "develop", sha: "a".repeat(40) },
      { name: "storefront", ref: "main", sha: "b".repeat(40) },
    ];
    expect(parseLock(renderLock(entries))).toEqual(entries);
  });

  it("returns an empty list for unrelated content", () => {
    expect(parseLock("not: a lock file\n")).toEqual([]);
  });
});
