import type { WorkspaceManifest } from "./manifest.ts";

/**
 * Marker line present in every generated file. `audit` and `manifest sync
 * --check` use full-content comparison, but the marker tells humans (and
 * agents) that hand edits will be overwritten.
 */
export const GENERATED_MARKER = "<!-- GENERATED by the workspaces skill from workspace.yaml.";

/**
 * A member SHA captured by `manifest freeze`.
 */
export type LockEntry = {
  name: string;
  ref: string;
  sha: string;
};

/**
 * Renders the workspace hub's CLAUDE.md from the manifest. The output is
 * fully deterministic: identical manifests produce identical files, so
 * staleness is detectable by comparison.
 */
export const renderClaudeMd = (manifest: WorkspaceManifest): string => {
  const layerRows = manifest.layers
    .map(
      (layer, index) =>
        `| ${index + 1} | ${layer.name} | \`${layer.path}\` | ${layer.description} |`,
    )
    .join("\n");
  const memberRows = manifest.members
    .map(
      (member) =>
        `| ${member.name} | \`${member.path}\` | \`${member.ref}\` | ${member.url ?? "(none)"} |`,
    )
    .join("\n");
  const skillLines =
    manifest.skills.length > 0
      ? manifest.skills.map((skill) => `- \`${skill}\` (in \`skills/${skill}/\`)`).join("\n")
      : "- (none registered)";
  // Manifest-declared sections render last, after everything the renderer
  // owns, so a hub can describe what the fixed schema cannot without any
  // hand edit to the generated file. Empty list renders nothing, which keeps
  // output byte-identical for hubs that declare none.
  const sectionBlocks = manifest.sections
    .map((section) => `\n## ${section.title}\n\n${section.body.trim()}\n`)
    .join("");

  return `${GENERATED_MARKER}
     Do not edit by hand: edit workspace.yaml, then run \`just sync\`. -->

# ${manifest.name} workspace

${manifest.description}

This repository is a workspace hub. It owns the documentation, decisions,
planning, and agent context for a multi-repo body of work. It is a developer
workflow tool: member repositories carry no committed workflow artifacts.

## Context layers

Load these in order when starting work here (the \`enter\` flow of the
workspaces skill automates this):

| # | Layer | Path | Purpose |
| - | ----- | ---- | ------- |
${layerRows}

The curated index at \`docs/index.md\` annotates everything an agent may load.
If a document is not reachable from the index, it is not workspace context.

## Workspace memory

Before starting any work, read the memory index at \`.claude/memory/MEMORY.md\`
and the entries touching your task. Record new knowledge there the moment it
surfaces (ideas, rejections, surprises, open questions); settled entries
graduate to an ADR, journal entry, or finding. Memory files are committed.

## Member repositories

Paths are relative to this directory (sibling checkouts).

| Member | Path | Base ref | Remote |
| ------ | ---- | -------- | ------ |
${memberRows}

## Conventions

- Stack names in member repos: \`${manifest.stackPrefix}<task-slug>\`; branches: \`${manifest.branchPrefix}<task-slug>\`.
- ADRs live in \`docs/adr/\` and are superseded, never edited.
- Every deviation from recorded plans/decisions gets a \`JOURNAL.md\` entry
  before or with the change.
- Work plans live in the hub; member repos never hold committed plan files.
- This file is generated. Edit \`workspace.yaml\` and run \`just sync\`.

## Workspace skills

${skillLines}

## Commands

Run \`just\` to list tasks. Core recipes: \`just sync\`, \`just status\`,
\`just audit\`, \`just freeze\`, \`just journal\`.
${sectionBlocks}`;
};

/**
 * Renders `workspace.lock` from captured member SHAs, sorted by member name
 * for deterministic output.
 */
export const renderLock = (entries: LockEntry[]): string => {
  const sorted = entries.toSorted((a, b) => a.name.localeCompare(b.name));
  const lines = sorted.map(
    (entry) => `  - name: ${entry.name}\n    ref: ${entry.ref}\n    sha: ${entry.sha}`,
  );
  return `version: 1\nmembers:\n${lines.join("\n")}\n`;
};

/**
 * Parses a `workspace.lock` file rendered by `renderLock`. Returns an empty
 * list for content that does not match the expected shape.
 */
export const parseLock = (content: string): LockEntry[] => {
  const entries: LockEntry[] = [];
  let current: Partial<LockEntry> = {};
  for (const line of content.split("\n")) {
    const nameMatch = line.match(/^ {2}- name: (.+)$/);
    if (nameMatch?.[1]) {
      current = { name: nameMatch[1].trim() };
      continue;
    }
    const refMatch = line.match(/^ {4}ref: (.+)$/);
    if (refMatch?.[1]) current.ref = refMatch[1].trim();
    const shaMatch = line.match(/^ {4}sha: (.+)$/);
    if (shaMatch?.[1]) {
      current.sha = shaMatch[1].trim();
      if (current.name && current.ref && current.sha) {
        entries.push({ name: current.name, ref: current.ref, sha: current.sha });
      }
      current = {};
    }
  }
  return entries;
};
